In [30]:
# imports
import pandas as pd
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score,accuracy_score,log_loss
import warnings
from sklearn.svm import SVC
warnings.filterwarnings('ignore')

In [14]:
glass_df = pd.read_csv(r'..\Cases\Glass Identification\Glass.csv')
glass_df.head()

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.0,0.0,building_windows_float_processed
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.0,0.0,building_windows_float_processed
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.0,0.0,building_windows_float_processed
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.0,0.0,building_windows_float_processed
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.0,0.0,building_windows_float_processed

In [31]:
X= glass_df.drop(columns=['Type'])
y= glass_df['Type']
scaler=StandardScaler()
le= LabelEncoder()
y= le.fit_transform(y)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=25,stratify=y)
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)
y_train

array([1, 0, 5, 1, 4, 0, 0, 2, 3, 0, 0, 3, 5, 1, 3, 0, 1, 4, 3, 1, 3, 4,
       0, 1, 1, 3, 0, 0, 0, 0, 1, 0, 0, 1, 1, 5, 0, 3, 0, 5, 0, 1, 1, 0,
       3, 1, 5, 0, 0, 1, 1, 3, 0, 2, 1, 1, 0, 5, 5, 0, 2, 0, 4, 5, 1, 1,
       0, 0, 1, 0, 1, 3, 3, 1, 1, 1, 1, 1, 2, 0, 1, 3, 0, 4, 4, 0, 0, 0,
       3, 5, 3, 2, 2, 1, 1, 2, 3, 1, 1, 1, 0, 5, 2, 0, 0, 2, 1, 1, 3, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 3, 0, 1, 1, 1, 3, 1, 1, 0, 1, 1, 0, 1,
       5, 1, 1, 0, 1, 3, 0, 0, 0, 0, 5, 1, 1, 3, 1, 1, 0])

In [32]:
import numpy as np
scores=[]
c=np.linspace(0.01,5,20)
gamma=np.linspace(0.01,5,20)

degree=[2,3,4]
# for i in range(1,19):
for i in c:
    for d in degree: 
        for g in gamma:
            for o in ['ovo','ovr']:
                    svm=SVC(kernel='rbf',C=i,degree=d,probability=True,random_state=25,decision_function_shape=o,gamma=g)
                    svm.fit(X_train_scaled,y_train) 
                    y_pred=svm.predict(X_test_scaled)
                    y_pred_proba=svm.predict_proba(X_test)
                    scores.append([i,g,d,k,o,accuracy_score(y_test,y_pred),log_loss(y_test,y_pred_proba)])
scores_df=pd.DataFrame(scores,columns=['c','g','d','Kernel','decision_function_shape','Accuracy','log_loss'])
scores_df.sort_values(by='Accuracy',ascending=False,inplace=True)
scores_df.head()

,c,g,d,Kernel,decision_function_shape,Accuracy,log_loss
600,1.323158,0.010000,2,sigmoid,ovo,0.707692,2.033917
601,1.323158,0.010000,2,sigmoid,ovr,0.707692,2.033917
806,1.585789,0.797895,4,sigmoid,ovo,0.707692,1.742183
807,1.585789,0.797895,4,sigmoid,ovr,0.707692,1.742183
800,1.585789,0.010000,4,sigmoid,ovo,0.707692,2.119990