In [14]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay,roc_curve,roc_auc_score,log_loss
import matplotlib.pyplot as plt  
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.compose import make_column_selector,make_column_transformer

In [15]:
concrt_df = pd.read_csv(r'..\Cases\Boston Housing\Boston.csv')
concrt_df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [16]:
X= concrt_df.drop(columns=['medv'])
y= concrt_df['medv']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=25)

1. KNN without scaling

In [17]:
# calculate for 1,3,5,7,9
from sklearn.metrics import r2_score


scores=[]
for i in range(1,10,2):
    knn=KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train,y_train)
    y_pred=knn.predict(X_test)
    scores.append([i,(r2_score(y_test,y_pred))])
df_scores=pd.DataFrame(scores,columns=['neighbors','R2 score'])
df_scores.sort_values(by='R2 score',ascending=False,inplace=True)
df_scores

   neighbors  R2 score
0          1  0.438672
2          5  0.408442
3          7  0.408393
4          9  0.385063
1          3  0.345712

1. KNN with StandardScaler scaling

In [18]:
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=25)
ct1=make_column_transformer((scalar, X_train.columns), remainder='passthrough',verbose_feature_names_out=False)
ct1=ct1.set_output(transform='pandas')
X_train_scaled=ct1.fit_transform(X_train)
X_test_scaled=ct1.transform(X_test)

In [19]:
# calculate for 1,3,5,7,9
from sklearn.metrics import r2_score
scores=[]
for i in range(1,10,2):
    knn=KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train_scaled,y_train)
    y_pred=knn.predict(X_test_scaled)
    scores.append([i,(r2_score(y_test,y_pred))])
df_scores=pd.DataFrame(scores,columns=['neighbors','R2 score'])
df_scores.sort_values(by='R2 score',ascending=False,inplace=True)
df_scores

   neighbors  R2 score
1          3  0.766754
0          1  0.760042
2          5  0.728073
4          9  0.694511
3          7  0.689448

1. KNN with minmax scaling

In [20]:
from sklearn.preprocessing import MinMaxScaler

minmax_scalar = MinMaxScaler()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=25)

ct1=make_column_transformer((minmax_scalar, X_train.columns), remainder='passthrough',verbose_feature_names_out=False)
ct1=ct1.set_output(transform='pandas')
X_train_scaled=ct1.fit_transform(X_train)
x_test_scaled=ct1.transform(X_test)

In [21]:
from sklearn.metrics import r2_score
scores=[]
for i in range(1,10,2):
    knn=KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train_scaled,y_train)
    y_pred=knn.predict(x_test_scaled)
    scores.append([i,(r2_score(y_test,y_pred))])
df_scores=pd.DataFrame(scores,columns=['neighbors','R2 score'])
df_scores.sort_values(by='R2 score',ascending=False,inplace=True)
df_scores

   neighbors  R2 score
0          1  0.722451
2          5  0.722296
1          3  0.701673
3          7  0.685407
4          9  0.651158