In [44]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay,roc_curve,roc_auc_score,log_loss
import matplotlib.pyplot as plt  
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.compose import make_column_selector,make_column_transformer

In [45]:
concrt_df = pd.read_csv(r'..\Cases/Concrete Strength/Concrete_Data.csv')
concrt_df.head()

   Cement  Blast  Fly  Water  Superplasticizer  Coarse   Fine  Age  Strength
0   540.0    0.0  0.0  162.0               2.5  1040.0  676.0   28     79.99
1   540.0    0.0  0.0  162.0               2.5  1055.0  676.0   28     61.89
2   332.5  142.5  0.0  228.0               0.0   932.0  594.0  270     40.27
3   332.5  142.5  0.0  228.0               0.0   932.0  594.0  365     41.05
4   198.6  132.4  0.0  192.0               0.0   978.4  825.5  360     44.30

In [46]:
X= concrt_df.drop(columns=['Strength'])
y= concrt_df['Strength']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=25)

1. KNN without scaling

In [47]:
# calculate for 1,3,5,7,9
from sklearn.metrics import r2_score


scores=[]
for i in range(1,10,2):
    knn=KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train,y_train)
    y_pred=knn.predict(X_test)
    scores.append([i,(r2_score(y_test,y_pred))])
df_scores=pd.DataFrame(scores,columns=['neighbors','R2 score'])
df_scores.sort_values(by='R2 score',ascending=False,inplace=True)
df_scores

   neighbors  R2 score
2          5  0.716044
1          3  0.703263
3          7  0.676935
0          1  0.663015
4          9  0.652829

1. KNN with StandardScaler scaling

In [48]:
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=25)
ct1=make_column_transformer((scalar, X_train.columns), remainder='passthrough',verbose_feature_names_out=False)
ct1=ct1.set_output(transform='pandas')
X_train_scaled=ct1.fit_transform(X_train)
X_test_scaled=ct1.transform(X_test)

In [49]:
# calculate for 1,3,5,7,9
from sklearn.metrics import r2_score
scores=[]
for i in range(1,10,2):
    knn=KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train_scaled,y_train)
    y_pred=knn.predict(X_test_scaled)
    scores.append([i,(r2_score(y_test,y_pred))])
df_scores=pd.DataFrame(scores,columns=['neighbors','R2 score'])
df_scores.sort_values(by='R2 score',ascending=False,inplace=True)
df_scores

   neighbors  R2 score
2          5  0.718626
1          3  0.708024
3          7  0.704146
4          9  0.682474
0          1  0.648779

1. KNN with minmax scaling

In [50]:
from sklearn.preprocessing import MinMaxScaler

minmax_scalar = MinMaxScaler()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=25)

ct1=make_column_transformer((minmax_scalar, X_train.columns), remainder='passthrough',verbose_feature_names_out=False)
ct1=ct1.set_output(transform='pandas')
X_train_scaled=ct1.fit_transform(X_train)
x_test_scaled=ct1.transform(X_test)

In [51]:
from sklearn.metrics import r2_score
scores=[]
for i in range(1,10,2):
    knn=KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train_scaled,y_train)
    y_pred=knn.predict(x_test_scaled)
    scores.append([i,(r2_score(y_test,y_pred))])
df_scores=pd.DataFrame(scores,columns=['neighbors','R2 score'])
df_scores.sort_values(by='R2 score',ascending=False,inplace=True)
df_scores

   neighbors  R2 score
1          3  0.698128
3          7  0.690356
2          5  0.688959
4          9  0.674332
0          1  0.612859