In [15]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [10]:
df_milk = pd.read_csv(r'..\Datasets\milk.csv',index_col='Animal')
df_milk.head()

           water  protein  fat  lactose   ash
Animal
HORSE       90.1      2.6  1.0      6.9  0.35
ORANGUTAN   88.5      1.4  3.5      6.0  0.24
MONKEY      88.4      2.2  2.7      6.4  0.18
DONKEY      90.3      1.7  1.4      6.2  0.40
HIPPO       90.4      0.6  4.5      4.4  0.10

In [11]:
scaler=StandardScaler().set_output(transform='pandas')
scaler.fit(df_milk)

StandardScaler()

In [13]:
scaled_milk=scaler.transform(df_milk)
scaled_milk.describe()

              water       protein           fat       lactose           ash
count  2.500000e+01  2.500000e+01  2.500000e+01  2.500000e+01  2.500000e+01
mean  -9.059420e-16  1.332268e-16 -3.552714e-17 -3.996803e-16  3.996803e-17
std    1.020621e+00  1.020621e+00  1.020621e+00  1.020621e+00  1.020621e+00
min   -2.650224e+00 -1.568145e+00 -9.032079e-01 -2.302182e+00 -1.542988e+00
25%   -5.481355e-01 -8.975199e-01 -6.703223e-01 -7.978519e-01 -6.736418e-01
50%    3.038473e-01 -8.718126e-02 -3.889189e-01  3.164664e-01 -1.277736e-01
75%    7.577073e-01  9.746418e-01  2.709235e-01  8.179097e-01  4.787467e-01
max    9.726936e-01  1.701152e+00  3.075254e+00  1.542217e+00  2.904828e+00

### using minmax scaller

In [16]:
scaler_minmax=MinMaxScaler().set_output(transform='pandas')
scaler_minmax.fit(df_milk)
minmax_scaled_milk=scaler_minmax.transform(df_milk)
minmax_scaled_milk.describe()

           water    protein        fat    lactose        ash
count  25.000000  25.000000  25.000000  25.000000  25.000000
mean    0.731516   0.479658   0.227024   0.598841   0.346909
std     0.281712   0.312184   0.256537   0.265483   0.229466
min     0.000000   0.000000   0.000000   0.000000   0.000000
25%     0.580220   0.205128   0.058537   0.391304   0.195455
50%     0.815385   0.452991   0.129268   0.681159   0.318182
75%     0.940659   0.777778   0.295122   0.811594   0.454545
max     1.000000   1.000000   1.000000   1.000000   1.000000